#  docker-compose.yml

version: '3'
services:
  mysql:
    image: mysql
    volumes:
      - db-data:/var/lib/mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      DATABASE: rna
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      UPLOAD_LIMIT: 64M
    ports:
      - 8080:80
 
  web:
    build:
      context: ./src
      dockerfile: ../Dockerfile
    ports:  
      - 5000:5000
    volumes:
      - ./src:/app
    environment:
      - DATABASE_URL=mysql://root@mysql:3306/rna
    depends_on:
      - mysql

volumes:
  db-data: